export const LOCATION_DATA: Record<string, Record<string, string[]>> = {
  India: {
    "Andhra Pradesh": ["Visakhapatnam", "Vijayawada", "Guntur", "Nellore", "Kurnool", "Tirupati"],
    "Arunachal Pradesh": ["Itanagar", "Naharlagun"],
    Assam: ["Guwahati", "Silchar", "Dibrugarh", "Jorhat"],
    Bihar: ["Patna", "Gaya", "Muzaffarpur", "Bhagalpur", "Darbhanga"],
    Chhattisgarh: ["Raipur", "Bhilai", "Bilaspur", "Durg"],
    Goa: ["Panaji", "Margao", "Vasco da Gama"],
    Gujarat: ["Ahmedabad", "Surat", "Vadodara", "Rajkot", "Bhavnagar", "Jamnagar"],
    Haryana: ["Gurugram", "Faridabad", "Rohtak", "Panipat", "Ambala", "Hisar"],
    "Himachal Pradesh": ["Shimla", "Manali", "Dharamsala", "Solan"],
    Jharkhand: ["Ranchi", "Jamshedpur", "Dhanbad", "Bokaro"],
    Karnataka: ["Bengaluru", "Mysuru", "Hubballi", "Mangaluru", "Belagavi", "Davangere"],
    Kerala: ["Thiruvananthapuram", "Kochi", "Kozhikode", "Thrissur", "Kollam"],
    "Madhya Pradesh": ["Bhopal", "Indore", "Jabalpur", "Gwalior", "Ujjain"],
    Maharashtra: ["Mumbai", "Pune", "Nagpur", "Nashik", "Aurangabad", "Solapur", "Thane"],
    Manipur: ["Imphal", "Thoubal"],
    Meghalaya: ["Shillong", "Tura"],
    Mizoram: ["Aizawl", "Lunglei"],
    Nagaland: ["Kohima", "Dimapur"],
    Odisha: ["Bhubaneswar", "Cuttack", "Rourkela", "Berhampur"],
    Punjab: ["Ludhiana", "Amritsar", "Jalandhar", "Patiala", "Bathinda"],
    Rajasthan: ["Jaipur", "Jodhpur", "Udaipur", "Kota", "Ajmer", "Bikaner"],
    Sikkim: ["Gangtok", "Namchi"],
    "Tamil Nadu": ["Chennai", "Coimbatore", "Madurai", "Tiruchirappalli", "Salem", "Tirunelveli"],
    Telangana: ["Hyderabad", "Warangal", "Nizamabad", "Karimnagar"],
    Tripura: ["Agartala", "Udaipur"],
    "Uttar Pradesh": ["Lucknow", "Kanpur", "Agra", "Varanasi", "Prayagraj", "Meerut", "Noida", "Ghaziabad"],
    Uttarakhand: ["Dehradun", "Haridwar", "Rishikesh", "Roorkee"],
    "West Bengal": ["Kolkata", "Howrah", "Durgapur", "Siliguri", "Asansol"],
    Delhi: ["New Delhi", "Delhi"],
    Chandigarh: ["Chandigarh"],
    "Jammu & Kashmir": ["Srinagar", "Jammu"],
    Ladakh: ["Leh", "Kargil"],
    Puducherry: ["Puducherry", "Karaikal"],
  },
  "United States": {
    California: ["Los Angeles", "San Francisco", "San Diego", "San Jose", "Sacramento", "Fresno"],
    Texas: ["Houston", "Dallas", "Austin", "San Antonio", "Fort Worth", "El Paso"],
    "New York": ["New York City", "Buffalo", "Albany", "Rochester", "Yonkers"],
    Florida: ["Miami", "Orlando", "Tampa", "Jacksonville", "St. Petersburg"],
    Illinois: ["Chicago", "Aurora", "Springfield", "Naperville"],
    Washington: ["Seattle", "Spokane", "Tacoma", "Bellevue"],
    Georgia: ["Atlanta", "Savannah", "Columbus", "Augusta"],
    Massachusetts: ["Boston", "Worcester", "Cambridge", "Springfield"],
    Pennsylvania: ["Philadelphia", "Pittsburgh", "Allentown", "Erie"],
    Ohio: ["Columbus", "Cleveland", "Cincinnati", "Toledo"],
    Michigan: ["Detroit", "Grand Rapids", "Lansing", "Ann Arbor"],
    "New Jersey": ["Newark", "Jersey City", "Trenton", "Paterson"],
    Arizona: ["Phoenix", "Tucson", "Scottsdale", "Mesa"],
    Colorado: ["Denver", "Colorado Springs", "Aurora", "Boulder"],
    "North Carolina": ["Charlotte", "Raleigh", "Greensboro", "Durham"],
    Virginia: ["Virginia Beach", "Norfolk", "Richmond", "Arlington"],
    Tennessee: ["Nashville", "Memphis", "Knoxville", "Chattanooga"],
  },
  "United Arab Emirates": {
    "Abu Dhabi": ["Abu Dhabi", "Al Ain", "Ruwais"],
    Dubai: ["Dubai", "Jebel Ali"],
    Sharjah: ["Sharjah", "Khor Fakkan"],
    Ajman: ["Ajman"],
    "Ras Al Khaimah": ["Ras Al Khaimah"],
    Fujairah: ["Fujairah"],
    "Umm Al Quwain": ["Umm Al Quwain"],
  },
  "United Kingdom": {
    England: ["London", "Manchester", "Birmingham", "Leeds", "Sheffield", "Bristol", "Liverpool"],
    Scotland: ["Edinburgh", "Glasgow", "Aberdeen", "Dundee"],
    Wales: ["Cardiff", "Swansea", "Newport"],
    "Northern Ireland": ["Belfast", "Derry"],
  },
  Singapore: {
    "Central Region": ["Singapore CBD", "Orchard", "Marina Bay"],
    "North Region": ["Woodlands", "Yishun", "Sembawang"],
    "East Region": ["Tampines", "Bedok", "Pasir Ris"],
    "West Region": ["Jurong", "Clementi", "Buona Vista"],
    "North-East Region": ["Hougang", "Sengkang", "Punggol"],
  },
  Australia: {
    "New South Wales": ["Sydney", "Newcastle", "Wollongong", "Central Coast"],
    Victoria: ["Melbourne", "Geelong", "Ballarat", "Bendigo"],
    Queensland: ["Brisbane", "Gold Coast", "Cairns", "Townsville", "Sunshine Coast"],
    "Western Australia": ["Perth", "Fremantle", "Bunbury", "Geraldton"],
    "South Australia": ["Adelaide", "Port Augusta", "Whyalla"],
    Tasmania: ["Hobart", "Launceston", "Devonport"],
    "Northern Territory": ["Darwin", "Alice Springs"],
    "Australian Capital Territory": ["Canberra"],
  },
  Canada: {
    Ontario: ["Toronto", "Ottawa", "Mississauga", "Hamilton", "Brampton"],
    Quebec: ["Montreal", "Quebec City", "Laval", "Gatineau"],
    "British Columbia": ["Vancouver", "Victoria", "Burnaby", "Surrey"],
    Alberta: ["Calgary", "Edmonton", "Red Deer"],
    Manitoba: ["Winnipeg", "Brandon"],
    Saskatchewan: ["Saskatoon", "Regina"],
    "Nova Scotia": ["Halifax", "Sydney"],
    "New Brunswick": ["Fredericton", "Moncton", "Saint John"],
  },
  Japan: {
    Tokyo: ["Tokyo", "Shinjuku", "Shibuya", "Akihabara"],
    Osaka: ["Osaka", "Sakai", "Namba"],
    Kanagawa: ["Yokohama", "Kawasaki", "Sagamihara"],
    Aichi: ["Nagoya", "Toyota"],
    Hokkaido: ["Sapporo", "Hakodate"],
    Fukuoka: ["Fukuoka", "Kitakyushu"],
    Hyogo: ["Kobe", "Himeji"],
    Kyoto: ["Kyoto", "Uji"],
    Hiroshima: ["Hiroshima", "Fukuyama"],
    Miyagi: ["Sendai"],
  },
  China: {
    Beijing: ["Beijing", "Haidian", "Chaoyang"],
    Shanghai: ["Shanghai", "Pudong"],
    Guangdong: ["Guangzhou", "Shenzhen", "Dongguan", "Foshan"],
    Shandong: ["Jinan", "Qingdao", "Weifang"],
    Zhejiang: ["Hangzhou", "Ningbo", "Wenzhou"],
    Jiangsu: ["Nanjing", "Suzhou", "Wuxi"],
    Sichuan: ["Chengdu", "Mianyang"],
    Hubei: ["Wuhan", "Yichang"],
    Hunan: ["Changsha", "Zhuzhou"],
    Fujian: ["Fuzhou", "Xiamen", "Quanzhou"],
  },
  "Saudi Arabia": {
    Riyadh: ["Riyadh", "Al Kharj"],
    Makkah: ["Jeddah", "Mecca", "Taif"],
    Madinah: ["Madinah", "Yanbu"],
    "Eastern Province": ["Dammam", "Al Khobar", "Dhahran", "Jubail"],
    Asir: ["Abha", "Khamis Mushait"],
    Tabuk: ["Tabuk"],
    Hail: ["Hail"],
    Qassim: ["Buraydah"],
  },
  Switzerland: {
    Zurich: ["Zurich", "Winterthur"],
    Bern: ["Bern", "Biel"],
    Vaud: ["Lausanne", "Montreux"],
    Geneva: ["Geneva"],
    "Basel-City": ["Basel"],
    Aargau: ["Aarau", "Baden"],
    "St. Gallen": ["St. Gallen"],
    Lucerne: ["Lucerne"],
    Valais: ["Sion"],
    Ticino: ["Lugano"],
  },
  Germany: {
    Bavaria: ["Munich", "Nuremberg", "Augsburg", "Regensburg"],
    "North Rhine-Westphalia": ["Cologne", "Düsseldorf", "Dortmund", "Essen", "Bochum"],
    "Baden-Württemberg": ["Stuttgart", "Karlsruhe", "Freiburg", "Mannheim"],
    Berlin: ["Berlin"],
    Hamburg: ["Hamburg"],
    "Lower Saxony": ["Hanover", "Brunswick", "Osnabrück"],
    Saxony: ["Dresden", "Leipzig", "Chemnitz"],
    Hesse: ["Frankfurt", "Wiesbaden", "Kassel"],
    "Rhineland-Palatinate": ["Mainz", "Ludwigshafen"],
    Thuringia: ["Erfurt", "Jena"],
  },
  France: {
    "Île-de-France": ["Paris", "Versailles", "Boulogne-Billancourt"],
    "Auvergne-Rhône-Alpes": ["Lyon", "Grenoble", "Clermont-Ferrand", "Saint-Étienne"],
    "Provence-Alpes-Côte d'Azur": ["Marseille", "Nice", "Toulon", "Aix-en-Provence"],
    "Nouvelle-Aquitaine": ["Bordeaux", "Limoges", "Pau"],
    Occitanie: ["Toulouse", "Montpellier", "Nîmes"],
    "Hauts-de-France": ["Lille", "Amiens"],
    Bretagne: ["Rennes", "Brest", "Nantes"],
    "Pays de la Loire": ["Nantes", "Le Mans", "Angers"],
    Normandie: ["Rouen", "Caen"],
    "Grand Est": ["Strasbourg", "Reims", "Metz"],
  },
};

export const COUNTRIES = Object.keys(LOCATION_DATA);

export function getStates(country: string): string[] {
  return Object.keys(LOCATION_DATA[country] ?? {});
}

export function getCities(country: string, state: string): string[] {
  return LOCATION_DATA[country]?.[state] ?? [];
}
